=== aroback/portfolio/papers/quals/COM541/blackhawks_news_article.dtd
<?xml version="1.0" ?>

<!ELEMENT news (news_item+)>

<!ELEMENT news_item (dateline, byline, article)>
<!ATTLIST news_item xmlns CDATA #REQUIRED>
<!ATTLIST news_item item CDATA #REQUIRED>
<!ATTLIST news_item title CDATA #REQUIRED>


<!ELEMENT dateline (date, time, am_pm, newstype, location)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT am_pm (#PCDATA)>
<!ELEMENT newstype (#PCDATA)>
<!ELEMENT location (#PCDATA)>

<!ELEMENT byline (author, title)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT article (player*, coach*, front_office*)>

<!ELEMENT player (p_team+, p_quotation*)*>
<!ATTLIST player xmlns CDATA #REQUIRED>
<!ATTLIST player name CDATA #REQUIRED>
<!ELEMENT p_team (p_team_name+)>
<!ELEMENT p_team_name (#PCDATA)>
<!ELEMENT p_quotation (#PCDATA)>

<!ELEMENT coach (c_team+, c_quotation*)*>
<!ATTLIST coach xmlns CDATA #REQUIRED>
<!ATTLIST coach name CDATA #REQUIRED>
<!ELEMENT c_team (c_team_name+)>
<!ELEMENT c_team_name (#PCDATA)>
<!ELEMENT c_quotation (#PCDATA)>

<!ELEMENT front_office (fo_team+, fo_quotation*)>
<!ATTLIST front_office xmlns CDATA #REQUIRED>
<!ATTLIST front_office name CDATA #REQUIRED>
<!ELEMENT fo_team (fo_team_name+)>
<!ELEMENT fo_team_name (#PCDATA)>
<!ELEMENT fo_quotation (#PCDATA)>

=== aroback/portfolio/papers/quals/COM541/instance_document.xml
<?xml version="1.0"?>

<!DOCTYPE news SYSTEM "http://mypages.iit.edu/~aroback/blackhawks_news_article.dtd">

<news>

	<news_item xmlns="http://blackhawks.nhl.com/club/news.htm?id=518045" item="1" title="Despite Win Team USA Must Pass Chemistry Test" >
		
		<dateline>
			<date>Wednesday, 02.17.2010</date>
			<time>4:53</time>
			<am_pm>PM</am_pm>
			<newstype>News</newstype>
			<location>VANCOUVER</location>
		</dateline>
		
		<byline>
			<author>Shawn P. Roarke</author>
			<title>NHL.com Managing Editor</title>
		</byline>
		
		<article>

					
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/David_Backes" name="David Backes" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>St. Louis Blues</p_team_name>
					</p_team>
					<p_quotation>"A win's a win, but we've got a lot of work to do to be where we want to be,"</p_quotation>
				</player>
		
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Patrick_Kane" name="Patrick Kane" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Chicago Blackhawks</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Zach_Parise" name="Zach Parise" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>New Jersey Devils</p_team_name>
					</p_team>
					<p_quotation/>
				</player>

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Paul_Stastny" name="Paul Stastny" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Colorado Avalanche</p_team_name>
					</p_team>
					<p_quotation/>
				</player>		

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Jamie_Langenbrunner" name="Jamie Langenbrunner" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>New Jersey Devils</p_team_name>
					</p_team>
					<p_quotation>"I think we're going to have to realize the situation of games a little better," U.S. captain Jamie Langenbrunner told NHL.com. "We got caught on some two-on-ones and three-on-twos late in the game, which we can't do. We have to realize the time and the score and play accordingly, play winning hockey. That'll come.
 
"Everybody wants to do their best out there and create things, and the more we get relaxed and the more we feel comfortable, we'll get better."</p_quotation>
				</player>					
				
				<coach xmlns="http://mypages.iit.edu/~aroback/c_name/Ron_Wilson" name="Ron Wilson" >
					<c_team>
						<c_team_name>Team USA Olympics</c_team_name>
						<c_team_name>Toronto Maple Leafs</c_team_name>
					</c_team>
					<c_quotation>"Yes, there are things we have to work on," Wilson said less than an hour after the win. "We have a game against Norway and they will provide a different set of problems."</c_quotation>
					<c_quotation>"You can't have a 35-minute practice and have everything work and clicking," the Toronto Maple Leafs coach said. "You don't have anybody that plays on the same line on their NHL teams."</c_quotation>
					<c_quotation>"We have to shoot the puck more and maybe be a little more selfish," Wilson said.</c_quotation>
				</coach>

				<front_office xmlns="http://mypages.iit.edu/~aroback/fo_name/Brian_Burke" name="Brian Burke">
				<fo_team>
					<fo_team_name>Team USA Olympics</fo_team_name>
					<fo_team_name>Toronto Maple Leafs</fo_team_name>
				</fo_team>
				<fo_quotation>"I thought the Swiss did a really good job in their D-zone positioning when that line had the puck, so I don't think they had a lot of chances," Team USA GM Brian Burke said. "But they had good puck possession and good puck movement. They just didn't generate a lot of offense. That will come. I thought we over-passed the puck a lot today."</fo_quotation>
				</front_office>
				
		</article>
		
	</news_item>
	
	<news_item xmlns="http://blackhawks.nhl.com/club/news.htm?id=518012" item="2" title="Blackhawks Sign Cullimore, Assign Him To Rockford" >
		
		<dateline>
			<date>Wednesday, 02.17.2010</date>
			<time>12:23</time>
			<am_pm>PM</am_pm>
			<newstype>News</newstype>
			<location/>
		</dateline>
		
		<byline>
			<author>Chicago Blackhawks</author>
			<title/>
		</byline>
		
		<article>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Jassen_Cullimore" name="Jassen Cullimore" >
					<p_team>
						<p_team_name>Chicago Blackhawks</p_team_name>
						<p_team_name>Rockford IceHogs</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				
				
		</article>
	
	</news_item>

	<news_item xmlns="http://blackhawks.nhl.com/club/news.htm?id=517926" item="3" title="Team USA Beats Switzerland 3-1 In Olympic Opener" >
		
		<dateline>
			<date>Tuesday, 02.16.2010</date>
			<time>5:29</time>
			<am_pm>PM</am_pm>
			<newstype>News</newstype>
			<location>VANCOUVER</location>
		</dateline>
		
		<byline>
			<author>Shawn P. Roarke</author>
			<title>NHL.com Managing Editor</title>
		</byline>
		
		<article>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Ryan_Miller" name="Ryan Miller" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Buffalo Sabres</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Roman_Wick" name="Roman Wick" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>Ottowa Senators</p_team_name>
					</p_team>
					<p_quotation/>
				</player>		

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/David_Backes" name="David Backes" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>St. Louis Blues</p_team_name>
					</p_team>
					<p_quotation/>
				</player>

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Jonas Hiller" name="JonasHiller" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>Anaheim Ducks</p_team_name>
					</p_team>
					<p_quotation/>
				</player>

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Ryan_Malone" name="Ryan Malone" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Tampa Bay Lightening</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Joe_Pavelski" name="Joe Pavelski" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>San Jose Sharks</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Phil_Kessel" name="Phil Kessel" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Toronto Maple Leafs</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Ryan_Suter" name="Ryan Suter" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Nashville Predators</p_team_name>
					</p_team>
					<p_quotation/>
				</player>

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Ivo_Ruthemann" name="Ivo Ruthemann" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
					</p_team>
					<p_quotation/>
				</player>

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Yannick_Weber" name="Yannick Weber" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>Hamilton Bulldogs</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Mark_Streit" name="Mark Streit" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>New York Islanders</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Chris_Drury" name="Chris Drury" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>New York Rangers</p_team_name>
					</p_team>
					<p_quotation/>
				</player>	

				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Thierry_Paterlini" name="Thierry Paterlini" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>ZSC Lions Switzerland</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Rafael_Diaz" name="Rafael Diaz" >
					<p_team>
						<p_team_name>Team Switzerland Olympics</p_team_name>
						<p_team_name>EV Zug Switzerland</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Patrick_Kane" name="Patrick Kane" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>Chicago Blackhawks</p_team_name>
					</p_team>
					<p_quotation/>
				</player>
				
				<player xmlns="http://mypages.iit.edu/~aroback/p_name/Zach_Parise" name="Zach Parise" >
					<p_team>
						<p_team_name>Team USA Olympics</p_team_name>
						<p_team_name>New Jersey Devils</p_team_name>
					</p_team>
					<p_quotation/>
				</player>				
				
				<front_office xmlns="http://mypages.iit.edu/~aroback/fo_name/Brian_Burke" name="Brian Burke">
				<fo_team>
					<fo_team_name>Team USA Olympics</fo_team_name>
					<fo_team_name>Toronto Maple Leafs</fo_team_name>
				</fo_team>
				<fo_quotation></fo_quotation>
				</front_office>
				
		</article>
		
	</news_item>
	
	<news_item xmlns="http://blackhawks.nhl.com/club/news.htm?id=517785" item="4" title="Comcast SportsNet Announces Blackhawks Programming During Olympics Break Network to air top 2009-10 Game Replays, 'Blackhawks TV,' 'SportsNite' features and a New, Half-Hour Special during Winter Olympics Break" >
		
		<dateline>
			<date>Wednesday, 02.17.2010</date>
			<time>4:35</time>
			<am_pm>PM</am_pm>
			<newstype>News</newstype>
